---
log_filepath:
  description: Path to the file, relative to working directory, where the log will be stored
  value: ./cert_processing_log.txt
smallest_certificate_id_to_connect:
  description: During validation we don't connect certificates with number lower than
    _this_ to connections
  value: 40
year_difference_between_validations:
  description: During validation we don't connect certificates with validation dates
    difference higher than _this_
  value: 5
use_text_with_newlines_during_parsing:
  description: During keyword search, search in text with newlines
  value: true
n_threads:
  description: How many threads to use for parallel computations
  value: 8
cc_cpe_matching_threshold:
  description: Level of required string similarity between CPE and certificate name on CC CPE matching, 0-100. Lower values yield more false negatives, higher values more false positives
  value: 70
cc_cpe_max_matches:
  description: Maximum number of candidate CPE items that may be related to given certificate, >0
  value: 20
cc_latest_snapshot:
  description: Url from where to fetch the latest snapshot of fully processed CC dataset
  value: https://www.ajanovsky.cz/cc_latest_snapshot.json