name: "Build docs"
on:
  push:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install external dependencies
        run: sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python3-dev -y
      - name: Install sec-certs and deps
        run: |
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev_requirements.txt
          pip install -e .
      - name: Build docs
        run: |
          cd docs
          make html
