name: "Build docs"
on:
  push:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: python -m pip install -r requirements/dev_requirements.txt
          docs-folder: "docs/"
