name: "Build docs"
on:
  push:
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install python dependencies
        run: |
          pip install -r requirements/dev_requirements.txt
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
