name: Lint (MyPy, Black, Ruff)
on:
  push:
  workflow_dispatch:
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install external dependencies
        run: sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python3-dev -y
      - name: Install python dependencies
        run: |
          pip install -r requirements/requirements.txt
          pip install -r requirements/dev_requirements.txt
      - name: Run mypy
        run: mypy .
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruf
      - name: Run Ruff
        run: ruff --format=github .
