name: Code analysis using mypy
on: [push]
jobs:
  run-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install mypy and types
        run: |
          pip install mypy
          mypy --install-types
      - name: Run mypy
        run: mypy --ignore-missing-imports *.py sec_certs/
