name: Lint (MyPy, Black, Ruff)
on:
  push:
  workflow_dispatch:
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements/dev_requirements.txt
      - name: Run Black
        run: black
        with:
          version: "23.1.0"
          options: "--check --target-version py38"
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements/dev_requirements.txt
      - name: Run Ruff
        run: ruff --format=github .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements/dev_requirements.txt
      - name: Run Mypy
        run: mypy .
