name: Lint (MyPy, Black, Ruff)
on:
  push:
  workflow_dispatch:
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          sudo apt-get install build-essential libpoppler-cpp-dev pkg-config python3-dev -y
          pip install -r requirements/dev_requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
