name: Tests
on:
  push:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install poppler-utils
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install pytest and package
        run: |
          pip install pytest
          pip install pytest-cov
          pip install ".[dev,test]"
      - name: Run tests
        run: pytest --cov sec_certs
